import { defineConfig, globalIgnores } from 'eslint/config';
import next from 'eslint-config-next';
import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';
import nextTypeScript from 'eslint-config-next/typescript';

/**
 * Flat config because ESLint 9 dropped `.eslintrc`, and because Next 16 removed
 * `next lint` in favour of running the ESLint CLI directly - which is what
 * `npm run lint` now does.
 *
 * `next-env.d.ts` is generated by Next and `coverage` is written by the test
 * run; neither is ours to lint.
 */
export default defineConfig([
  ...next,
  ...nextCoreWebVitals,
  ...nextTypeScript,
  globalIgnores(['.next/**', 'out/**', 'coverage/**', 'next-env.d.ts']),
]);
